name:  02-2 - Deploy

on:
  workflow_call:

jobs:
  AzureDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: actions/checkout@v3

      - name: Update Compose File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_LOGIN }}
          port: ${{ secrets.AZURE_PORT }}
          password: ${{ secrets.AZURE_PWD }}
        
          source: "./docker-compose.yml"
          target: "."

      - name: Update Compose File
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_LOGIN }}
          port: ${{ secrets.AZURE_PORT }}
          password: ${{ secrets.AZURE_PWD }}
        
          script: |
            echo ${{secrets.GOLF_TOKEN}} | docker login ghcr.io -u valentinwlt --password-stdin
            docker pull ghcr.io/valentinwlt/golf-back:jeanpeuplus
            docker pull ghcr.io/valentinwlt/golf-front:jeanpeuplus

            docker compose up -d          